
alg: TraC
alg_kwargs:
  # alpha: 0.8
  bc_coeff: 0.0
  bc_data: all
  # contrastive_bias: 0.75
  bc_steps: 30000

optim: Adam
optim_kwargs:
  lr: 0.0001

network: ActorPolicy
network_kwargs:
  actor_class: ContinuousMLPActor
  actor_kwargs:
    dropout: 0.25 # only actor gets dropout sometimes.
    output_act: ["import", "torch.nn", "Tanh"]
    hidden_layers: [256, 256]
    ortho_init: True

checkpoint: null

# eval_env: OfflineBallRun-v0

dataset: FeedbackBuffer
dataset_kwargs:
  # path: /root/autodl-tmp/.dsrl/pref_datasets/BallRun/SafetyBallRun-v0-10000-20-20-4.00.hdf5
  batch_size: 96
  segment_length: null # default to 64
  # segment_length: 64 # default to 64
  capacity: null # How many comparisons to allow, null means all in the dataset.
  # label_key: rl_sum
  # mode: comparison

processor: null

schedule:
  actor: linear_warmup
schedule_kwargs:
  actor:
    total_steps: 10000
    multiplier: 0.1

trainer_kwargs: # Arguments given to Algorithm.train
  total_steps: 100000 # The total number of steps to train
  log_freq: 100 # How often to log values
  profile_freq: 100
  eval_freq: 1000 # How often to run evals
  eval_fn: eval_policy
  eval_kwargs:
    num_ep: 20 # Number of enviornment episodes to run for evaluation, or -1 if none should be run.
  # loss_metric: reward # The validation metric that determines when to save the "best_checkpoint"
  # target_cost: 10
  train_dataloader_kwargs:
    num_workers: 2 # Number of dataloader workers.
    batch_size: null

# seed: null
